version: '3'
services:
  app:
    image: thor
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/src
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro