[tool.poetry]
name = "thor"
version = "0.0.1"
description = "Gen3 Release Orchestrator"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.65.1"
uvicorn = "^0.14.0"
gunicorn = "^20.1.0"
cdislogging = "^1.0.0"
jira = "3.0.0.0a0"
gen3git = {git = "https://github.com/uc-cdis/release-helper.git", rev = "gen3release"}
pygit2 = "^1.6.1"
SQLAlchemy = "^1.4.23"
psycopg2 = "^2.9.1"
pytest = "^6.2.4"
python-crontab = "^2.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
